import type { LocalizedText } from "@/lib/i18n";
import type { MediaAsset } from "@/lib/media";

export type TourPackage = {
  id: string;
  title: LocalizedText;
  family: LocalizedText;
  summary: LocalizedText;
  price: { status: "indicative"; currency: "USD"; label: LocalizedText };
  duration: LocalizedText;
  media: MediaAsset;
  highlights: LocalizedText[];
  experience: LocalizedText;
  itinerary: LocalizedText[];
  itineraryLabel: LocalizedText;
  included: LocalizedText;
  includedLabel: LocalizedText;
  priceDetail: LocalizedText;
  priceDetailLabel: LocalizedText;
};

const img = (name: string): MediaAsset => ({ url: `/media/incoming/${encodeURIComponent(name)}`, role: "atmosphere" });
const local = (ru: string, en: string): LocalizedText => ({ ru, en });
const highlights = (...items: Array<[string, string]>) => items.map(([ru, en]) => local(ru, en));

function tour(data: {
  id: string; ru: string; en: string; familyRu: string; familyEn: string; summaryRu: string; summaryEn: string;
  priceRu: string; priceEn: string; durationRu: string; durationEn: string; image: string;
  tags: Array<[string, string]>; stops: Array<[string, string]>; includedRu?: string; includedEn?: string; priceRuDetail?: string; priceEnDetail?: string;
  itineraryLabelRu?: string; itineraryLabelEn?: string; includedLabelRu?: string; includedLabelEn?: string; priceLabelRu?: string; priceLabelEn?: string;
}): TourPackage {
  const activityIds = new Set(["rafting", "fishing", "turtle-snorkeling", "surfing", "safari", "batur-sunrise", "water-sports", "atv", "craft-jewellery", "romantic-dinner"]);
  const isActivity = activityIds.has(data.id);
  const itineraryLabel = isActivity
    ? local("Как проходит мероприятие", "How the experience works")
    : local("Маршрут и остановки", "Route and stops");
  const includedLabel = isActivity
    ? local("Что входит в мероприятие", "Experience inclusions")
    : local("Что включено", "What's included");
  const priceDetailLabel = isActivity
    ? local("Стоимость и опции", "Rates and options")
    : local("Условия цены", "Price terms");
  return {
    id: data.id, title: local(data.ru, data.en), family: local(data.familyRu, data.familyEn), summary: local(data.summaryRu, data.summaryEn),
    price: { status: "indicative", currency: "USD", label: local(data.priceRu, data.priceEn) }, duration: local(data.durationRu, data.durationEn),
    media: img(data.image), highlights: highlights(...data.tags), itinerary: highlights(...data.stops),
    itineraryLabel: data.itineraryLabelRu && data.itineraryLabelEn ? local(data.itineraryLabelRu, data.itineraryLabelEn) : itineraryLabel,
    experience: local(
      `Этот маршрут раскрывается постепенно: ${data.stops.map(([ru]) => ru.toLowerCase()).join(", ")}. Между остановками остаётся время почувствовать атмосферу места, сделать фотографии и путешествовать без спешки.`,
      `The experience unfolds through ${data.stops.map(([, en]) => en.toLowerCase()).join(", ")}. Between stops, there is time to take in the atmosphere, capture photographs, and travel without feeling rushed.`,
    ),
    included: local(data.includedRu || "Организация поездки и сопровождение по согласованной программе.", data.includedEn || "Trip arrangements and assistance for the agreed programme."),
    includedLabel: data.includedLabelRu && data.includedLabelEn ? local(data.includedLabelRu, data.includedLabelEn) : includedLabel,
    priceDetail: local(data.priceRuDetail || "Финальная стоимость зависит от даты, количества гостей и выбранных опций.", data.priceEnDetail || "Final price depends on date, group size, and selected options."),
    priceDetailLabel: data.priceLabelRu && data.priceLabelEn ? local(data.priceLabelRu, data.priceLabelEn) : priceDetailLabel,
  };
}

const terrace = "Bali rice terraces sunrise mist wide cinematic.jpg";
const east = "Tirta Gangga Bali water palace.jpg";
const waterfall = "Bali waterfall jungle vertical.jpg";
const uluwatu = "Uluwatu cliff sunset aerial.jpg";
const penida = "Kelingking beach aerial Bali.jpg";
const road = "Bali winding road tropical aerial.jpg";
const carving = "Balinese temple stone carving close up.jpg";
const hands = "Bali local hospitality hands detail.jpg";

const basePackages: TourPackage[] = [
  tour({id:"kintamani",ru:"Кинтамани и сердце Бали",en:"Kintamani & the heart of Bali",familyRu:"Хит",familyEn:"Bestseller",summaryRu:"Вулкан Батур, Убуд, рисовые террасы и водопад за один насыщенный день.",summaryEn:"Mount Batur views, Ubud, rice terraces, and a waterfall in one rewarding day.",priceRu:"$65 / авто",priceEn:"$65 / car",durationRu:"09:00–19:00",durationEn:"09:00–19:00",image:terrace,tags:[["Вулкан","Volcano"],["Убуд","Ubud"],["Террасы","Terraces"]],stops:[["Смотровая площадка Батур","Mount Batur viewpoint"],["Убуд и деревни мастеров","Ubud and artisan villages"],["Террасы и водопад","Rice terraces and waterfall"]],includedRu:"Частный автомобиль с кондиционером и водитель-гид.",includedEn:"Private air-conditioned car and driver-guide.",priceRuDetail:"До 4 гостей; +$6 за дополнительного гостя. Билеты отдельно.",priceEnDetail:"Up to 4 guests; +$6 per additional guest. Tickets excluded."}),
  tour({id:"northwest-bali",ru:"Северо-запад Бали",en:"Northwest Bali",familyRu:"Маршрут",familyEn:"Journey",summaryRu:"Озеро Братан, Улун Дану, Таман Аюн и водопады прохладного севера.",summaryEn:"Lake Bratan, Ulun Danu, Taman Ayun, and waterfalls in Bali's cooler north.",priceRu:"$65 / авто",priceEn:"$65 / car",durationRu:"09:00–20:00",durationEn:"09:00–20:00",image:waterfall,tags:[["Озёра","Lakes"],["Храмы","Temples"],["Водопады","Waterfalls"]],stops:[["Озеро Братан и Улун Дану","Lake Bratan and Ulun Danu"],["Таман Аюн","Taman Ayun"],["Водопад на севере","Northern waterfall"]]}),
  tour({id:"east-bali",ru:"Восточный Бали",en:"East Bali",familyRu:"Маршрут",familyEn:"Journey",summaryRu:"Водные дворцы, чёрный песок и культурные места восточного побережья.",summaryEn:"Water palaces, black-sand coast, and cultural landmarks of East Bali.",priceRu:"$65 / авто",priceEn:"$65 / car",durationRu:"09:00–20:00",durationEn:"09:00–20:00",image:east,tags:[["Тирта Ганга","Tirta Gangga"],["Таман Уджунг","Taman Ujung"],["Побережье","Coast"]],stops:[["Гоа Лавах","Goa Lawah"],["Таман Уджунг","Taman Ujung"],["Тирта Ганга","Tirta Gangga"]]}),
  tour({id:"temple-tour",ru:"Храмы Бали",en:"Temples of Bali",familyRu:"Культура",familyEn:"Culture",summaryRu:"Знаковые храмы на скалах и у океана в элегантном частном маршруте.",summaryEn:"Iconic cliffside and ocean temples on a relaxed private journey.",priceRu:"$65 / авто",priceEn:"$65 / car",durationRu:"9–10 часов",durationEn:"9–10 hours",image:carving,tags:[["Улувату","Uluwatu"],["Танах Лот","Tanah Lot"],["Таман Аюн","Taman Ayun"]],stops:[["Храм Улувату","Uluwatu Temple"],["Танах Лот","Tanah Lot"],["Таман Аюн","Taman Ayun"]]}),
  tour({id:"beach-tour",ru:"Пляжи Бали",en:"Bali Beach Journey",familyRu:"Побережье",familyEn:"Coast",summaryRu:"Лучшие пляжи Букита, впечатляющие скалы и закат над Индийским океаном.",summaryEn:"Bukit's best beaches, dramatic cliffs, and an Indian Ocean sunset.",priceRu:"$60 / авто",priceEn:"$60 / car",durationRu:"8–10 часов",durationEn:"8–10 hours",image:uluwatu,tags:[["Пандава","Pandawa"],["Паданг-Паданг","Padang Padang"],["Закат","Sunset"]],stops:[["Пандава или Баланган","Pandawa or Balangan"],["Паданг-Паданг","Padang Padang"],["Улувату на закате","Uluwatu at sunset"]],priceRuDetail:"До 4 гостей; +$6 за дополнительного гостя. Максимум 6 гостей.",priceEnDetail:"Up to 4 guests; +$6 per additional guest. Maximum 6 guests."}),
  tour({id:"rafting",ru:"Рафтинг в джунглях",en:"Jungle Rafting",familyRu:"Приключение",familyEn:"Adventure",summaryRu:"Сплав по Аюнгу или Телага Ваджа среди ущелий, леса и водопадов.",summaryEn:"Raft the Ayung or Telaga Waja through gorges, jungle, and waterfalls.",priceRu:"от $45 / гость",priceEn:"from $45 / guest",durationRu:"5–7 часов",durationEn:"5–7 hours",image:waterfall,tags:[["Река","River"],["Джунгли","Jungle"],["Активно","Active"]],stops:[["Трансфер к базе","Transfer to base"],["Инструктаж и сплав","Briefing and rafting"],["Душ и обед","Shower and lunch"]]}),
  tour({id:"fishing",ru:"Морская рыбалка",en:"Private Sea Fishing",familyRu:"Океан",familyEn:"Ocean",summaryRu:"Частный выход к Нуса-Пениде и Лембонгану с троллингом и снорклингом.",summaryEn:"Private trip to Nusa Penida and Lembongan with trolling and snorkeling.",priceRu:"$390 / 4 гостя",priceEn:"$390 / 4 guests",durationRu:"08:00–16:00",durationEn:"08:00–16:00",image:penida,tags:[["Троллинг","Trolling"],["Снорклинг","Snorkeling"],["Частный катер","Private boat"]],stops:[["Троллинг в открытом море","Offshore trolling"],["Коралловая рыбалка","Reef fishing"],["Снорклинг","Snorkeling"]]}),
  tour({id:"turtle-snorkeling",ru:"Черепаший остров и снорклинг",en:"Turtle Island & Snorkeling",familyRu:"Для семьи",familyEn:"Family",summaryRu:"Лёгкая морская прогулка, снорклинг и посещение черепашьего острова.",summaryEn:"An easy boat trip with snorkeling and a visit to Turtle Island.",priceRu:"$38 / гость",priceEn:"$38 / guest",durationRu:"3–4 часа",durationEn:"3–4 hours",image:penida,tags:[["Черепахи","Turtles"],["Лодка","Boat"],["Снорклинг","Snorkeling"]],stops:[["Трансфер из Нуса-Дуа","Pickup from Nusa Dua"],["Снорклинг","Snorkeling"],["Черепаший остров","Turtle Island"]]}),
  tour({id:"surfing",ru:"Индивидуальный серфинг",en:"Private Surf Lesson",familyRu:"Активность",familyEn:"Activity",summaryRu:"Персональное занятие для первого старта или уверенного прогресса на волне.",summaryEn:"A private lesson for your first ride or confident progression.",priceRu:"$70 / гость",priceEn:"$70 / guest",durationRu:"2 часа",durationEn:"2 hours",image:uluwatu,tags:[["Инструктор","Instructor"],["Доска","Board"],["Все уровни","All levels"]],stops:[["Подбор спота","Spot selection"],["Техника на берегу","Beach technique"],["Практика в воде","Water session"]]}),
  tour({id:"safari",ru:"Bali Safari",en:"Bali Safari",familyRu:"Для семьи",familyEn:"Family",summaryRu:"День среди животных, сафари-маршрутов и тропической природы парка.",summaryEn:"A day of wildlife, safari routes, and tropical park landscapes.",priceRu:"от $75 / гость",priceEn:"from $75 / guest",durationRu:"6–8 часов",durationEn:"6–8 hours",image:hands,tags:[["Животные","Wildlife"],["Семья","Family"],["Парк","Park"]],stops:[["Трансфер в парк","Transfer to park"],["Сафари и шоу","Safari and shows"],["Свободное время","Free time"]]}),
  tour({id:"batur-sunrise",ru:"Рассвет на Батуре",en:"Mount Batur Sunrise",familyRu:"Восхождение",familyEn:"Trekking",summaryRu:"Ночной старт и встреча рассвета на высоте 1717 метров.",summaryEn:"An early ascent to watch sunrise from 1,717 metres above sea level.",priceRu:"$80 / гость",priceEn:"$80 / guest",durationRu:"02:00–09:00",durationEn:"02:00–09:00",image:terrace,tags:[["Рассвет","Sunrise"],["Треккинг","Trekking"],["Вулкан","Volcano"]],stops:[["Ранний трансфер","Early transfer"],["Подъём с проводником","Guided ascent"],["Рассвет и возвращение","Sunrise and descent"]]}),
  tour({id:"water-sports",ru:"Водные развлечения",en:"Bali Water Sports",familyRu:"Активность",familyEn:"Activity",summaryRu:"Парасейлинг, гидроцикл, флайборд, дайвинг и другие активности в Беноа.",summaryEn:"Parasailing, jet ski, flyboard, diving, and more in Benoa Bay.",priceRu:"от $30",priceEn:"from $30",durationRu:"2–5 часов",durationEn:"2–5 hours",image:penida,tags:[["Парасейлинг","Parasailing"],["Jet ski","Jet ski"],["Дайвинг","Diving"]],stops:[["Трансфер в Беноа","Transfer to Benoa"],["Выбранные активности","Selected activities"],["Возвращение","Return transfer"]]}),
  tour({id:"atv",ru:"ATV по джунглям",en:"Bali ATV Adventure",familyRu:"Приключение",familyEn:"Adventure",summaryRu:"Маршрут через поля, реку, джунгли и участки с вулканическим песком.",summaryEn:"Ride through fields, river tracks, jungle, and volcanic-sand terrain.",priceRu:"от $65 / гость",priceEn:"from $65 / guest",durationRu:"4–6 часов",durationEn:"4–6 hours",image:road,tags:[["ATV","ATV"],["Джунгли","Jungle"],["Грязевой маршрут","Off-road"]],stops:[["Трансфер на базу","Transfer to base"],["Инструктаж","Safety briefing"],["Маршрут на ATV","ATV trail"]]}),
  tour({id:"nusa-penida",ru:"Нуса-Пенида",en:"Nusa Penida",familyRu:"Остров",familyEn:"Island",summaryRu:"Панорамы, пляжи и выбор западного, восточного или комбинированного маршрута.",summaryEn:"Clifftop views, beaches, and west, east, or combination itineraries.",priceRu:"$90 / гость",priceEn:"$90 / guest",durationRu:"06:00–18:00",durationEn:"06:00–18:00",image:penida,tags:[["Kelingking","Kelingking"],["Diamond Beach","Diamond Beach"],["Океан","Ocean"]],stops:[["Скоростной катер","Fast boat"],["Маршрут по острову","Island itinerary"],["Возвращение на Бали","Return to Bali"]]}),
  tour({id:"craft-jewellery",ru:"Мастерские и украшения",en:"Craft & Jewellery Studios",familyRu:"Культура",familyEn:"Culture",summaryRu:"Знакомство с балийским мастерством, кожей, серебром и авторскими изделиями.",summaryEn:"Discover Balinese craftsmanship, leather, silver, and artisan pieces.",priceRu:"по запросу",priceEn:"on request",durationRu:"3–5 часов",durationEn:"3–5 hours",image:carving,tags:[["Ремесло","Craft"],["Серебро","Silver"],["Дизайн","Design"]],stops:[["Выбранные мастерские","Selected workshops"],["Знакомство с процессом","Meet the makers"],["Время для выбора изделий","Time to browse"]]}),
  tour({id:"romantic-dinner",ru:"Ужин у океана",en:"Romantic Ocean Dinner",familyRu:"Для двоих",familyEn:"For two",summaryRu:"Закат и ужин с морепродуктами на берегу океана в Джимбаране.",summaryEn:"Sunset and a seafood dinner by the ocean in Jimbaran.",priceRu:"от $25 / стол",priceEn:"from $25 / table",durationRu:"2–3 часа",durationEn:"2–3 hours",image:uluwatu,tags:[["Закат","Sunset"],["Джимбаран","Jimbaran"],["Ужин","Dinner"]],stops:[["Трансфер в Джимбаран","Transfer to Jimbaran"],["Стол у океана","Oceanfront table"],["Ужин на закате","Sunset dinner"]]}),
  tour({id:"vehicle-rental",ru:"Автомобили и байки",en:"Cars & Scooters",familyRu:"Транспорт",familyEn:"Transport",summaryRu:"Подберём автомобиль, байк или транспорт с водителем под ваш маршрут.",summaryEn:"Choose a car, scooter, or chauffeured vehicle for your plans.",priceRu:"по запросу",priceEn:"on request",durationRu:"от 1 дня",durationEn:"from 1 day",image:road,tags:[["Авто","Car"],["Байк","Scooter"],["С водителем","With driver"]],stops:[["Скутеры 110–160 cc для ежедневных поездок","110–160cc scooters for everyday travel"],["Компактные и семейные автомобили с кондиционером","Air-conditioned compact and family cars"],["Автомобиль или минивэн с водителем","Car or minivan with a driver"],["Доставка к отелю или вилле по согласованию","Delivery to your hotel or villa by arrangement"]],itineraryLabelRu:"Варианты транспорта",itineraryLabelEn:"Vehicle options",includedLabelRu:"Сервис аренды",includedLabelEn:"Rental service",includedRu:"Подбор подходящей категории, проверка наличия, согласование доставки или получения и контакт для поддержки в период аренды.",includedEn:"Vehicle matching, availability confirmation, arranged delivery or collection, and a support contact throughout the rental period.",priceLabelRu:"Как рассчитывается аренда",priceLabelEn:"How rental pricing works",priceRuDetail:"Стоимость рассчитывается за сутки и зависит от категории, срока аренды, сезона, района доставки и выбора автомобиля с водителем или без. Депозит, документы и страховка подтверждаются до оплаты.",priceEnDetail:"Rates are calculated per day and depend on vehicle class, rental length, season, delivery area, and whether a driver is included. Deposit, licence requirements, and insurance are confirmed before payment."}),
  tour({id:"java-bromo-ijen",ru:"Ява: Бромо и Иджен",en:"Java: Bromo & Ijen",familyRu:"Экспедиция",familyEn:"Expedition",summaryRu:"Многодневное путешествие к двум легендарным вулканам Восточной Явы.",summaryEn:"A multi-day journey to two legendary volcanoes in East Java.",priceRu:"по запросу",priceEn:"on request",durationRu:"3 дня / 2 ночи",durationEn:"3 days / 2 nights",image:terrace,tags:[["Бромо","Bromo"],["Иджен","Ijen"],["Ява","Java"]],stops:[["Переезд на Яву","Transfer to Java"],["Рассвет на Бромо","Bromo sunrise"],["Кратер Иджен","Ijen crater"]]}),
  tour({id:"java-yogyakarta",ru:"Ява: Джокьякарта",en:"Java: Yogyakarta",familyRu:"Культура",familyEn:"Culture",summaryRu:"Боробудур, Прамбанан и культурная столица Явы в одной поездке.",summaryEn:"Borobudur, Prambanan, and Java's cultural capital in one journey.",priceRu:"по запросу",priceEn:"on request",durationRu:"3 дня / 2 ночи",durationEn:"3 days / 2 nights",image:carving,tags:[["Боробудур","Borobudur"],["Прамбанан","Prambanan"],["Джокьякарта","Yogyakarta"]],stops:[["Перелёт или переезд","Flight or transfer"],["Боробудур","Borobudur"],["Прамбанан и город","Prambanan and city"]]}),
];

const stories: Record<string, LocalizedText> = {
  kintamani: local("Утро начинается среди зелени Убуда, где дорога ведёт от мастерских и деревень к рисовым террасам. После водопада пейзаж постепенно становится горным, и день завершается панорамой вулкана Батур и его кальдеры.", "Begin among Ubud's villages and creative workshops before the landscape opens into rice terraces. After a waterfall stop, the road climbs into the highlands and ends with sweeping views across Mount Batur and its caldera."),
  "northwest-bali": local("Вы покидаете жаркое побережье и поднимаетесь в прохладные горы. Туман над озером Братан, отражения храма Улун Дану и зелёные дороги севера создают спокойный день, который ощущается совсем иначе, чем южный Бали.", "Leave the warm coast behind and climb into Bali's cooler highlands. Mist over Lake Bratan, the reflections of Ulun Danu, and green northern roads create a calm day far removed from the energy of the south."),
  "east-bali": local("Восток раскрывается через воду, камень и океан. Вы проходите по садам королевских дворцов, видите священные источники и заканчиваете день у менее людного побережья, где ритм острова остаётся неспешным.", "East Bali reveals itself through water, stone, and ocean. Walk through royal gardens, encounter sacred springs, and finish near a quieter coastline where the island still moves at an unhurried pace."),
  "temple-tour": local("Этот день соединяет три разных лица балийской духовности: тихие дворы королевского храма, Танах Лот среди океанских волн и Улувату на краю скалы. Между ними — рассказы о ритуалах, архитектуре и повседневной жизни острова.", "This day connects three expressions of Balinese spirituality: the quiet courtyards of a royal temple, Tanah Lot among the waves, and Uluwatu at the cliff's edge, with stories of ritual, architecture, and island life along the way."),
  "beach-tour": local("День строится вокруг света и океана. Вы выбираете пляжи под своё настроение, отдыхаете между известняковыми скалами, а к вечеру поднимаетесь выше, чтобы увидеть, как солнце уходит за горизонт Улувату.", "The day follows the light and the ocean. Choose beaches to suit your mood, pause between limestone cliffs, then move uphill in time to watch the sun sink beyond Uluwatu's horizon."),
  rafting: local("После инструктажа река быстро уводит вас вглубь джунглей. Пороги чередуются со спокойными участками, каменными ущельями и водопадами, а в конце ждут душ, сухая одежда и заслуженный обед.", "After a clear safety briefing, the river carries you deep into the jungle. Rapids alternate with quiet stretches, stone gorges, and waterfalls before a shower, dry clothes, and a well-earned lunch."),
  fishing: local("Катер выходит в море утром, когда вода спокойнее и горизонт особенно чистый. День сочетает троллинг, коралловую рыбалку и остановку для снорклинга; улов можно приготовить на острове по договорённости.", "Head offshore in the calmer morning light with a clear horizon ahead. The day blends trolling, reef fishing, and a snorkeling stop, with the option to have the catch prepared on the island."),
  "turtle-snorkeling": local("Небольшая лодка отправляется от Нуса-Дуа к спокойной воде для снорклинга, а затем к черепашьему острову. Это лёгкая морская прогулка без длинных переездов, особенно удобная для семей.", "A small boat leaves Nusa Dua for an easy snorkeling stop before continuing to Turtle Island. With no long overland journey, it is a relaxed ocean experience that works especially well for families."),
  surfing: local("Занятие начинается на берегу: инструктор объясняет позицию, безопасность и выбор волны. Затем всё переносится в воду — с персональными подсказками после каждой попытки, чтобы первая уверенная поездка случилась быстрее.", "Start on the sand with stance, safety, and wave selection, then take it into the water. Personal feedback after every attempt helps turn uncertainty into that first confident ride."),
  safari: local("В парке день проходит между сафари-маршрутом, просторными зонами животных и шоу по расписанию. Можно двигаться без спешки, выбирать интересные остановки и оставить время для семейного обеда.", "Move through the park's safari route, open wildlife areas, and scheduled presentations at an easy pace, choosing the stops that interest you and leaving room for a relaxed family lunch."),
  "batur-sunrise": local("Путешествие начинается ночью. Под светом фонарей тропа поднимается по вулканическому склону, а наверху темнота постепенно сменяется золотым светом над кальдерой и озером Батур.", "The journey begins in darkness. Follow the volcanic trail by torchlight until the sky slowly turns gold above the caldera and Lake Batur—a sunrise earned step by step."),
  "water-sports": local("Вы сами задаёте уровень энергии: от спокойной прогулки по воде до парасейлинга, гидроцикла или дайвинга. Комбинация активностей собирается заранее, чтобы на месте не терять время на выбор.", "Set the energy level yourself—from an easy boat ride to parasailing, jet ski, or diving. Activities are arranged in advance so your time by the water is spent enjoying them, not deciding what to do."),
  atv: local("После короткой тренировки маршрут уходит с асфальта на поля, лесные тропы и грязевые участки. Это не просто скорость: дорога постоянно меняется и показывает сельский Бали с неожиданной стороны.", "After a short practice session, leave the road for fields, forest trails, and muddy tracks. It is not only about speed—the changing terrain offers a completely different view of rural Bali."),
  "nusa-penida": local("Ранний катер пересекает пролив, а дальше остров раскрывается чередой огромных скал, белых пляжей и высоких обзорных точек. Выбирайте запад, восток или комбинированный маршрут в зависимости от темпа.", "An early fast boat crosses the strait before the island opens into immense cliffs, white beaches, and high viewpoints. Choose west, east, or a combination route depending on how much ground you want to cover."),
  "craft-jewellery": local("Вы заходите туда, где вещи создаются руками: в мастерские серебра, резьбы, кожи и локального дизайна. Мастера показывают процесс, а время для выбора изделий остаётся свободным и ненавязчивым.", "Step inside the places where objects are made by hand—silver, carving, leather, and local design studios. Makers share their process, with unhurried time to browse without pressure."),
  "romantic-dinner": local("Вечер начинается мягким светом над Джимбараном. Стол стоит прямо у моря, рыбу и морепродукты готовят рядом, а ужин развивается вместе с закатом и огнями рыбацкой бухты.", "The evening begins in Jimbaran's soft golden light. Your table sits beside the sea, seafood is prepared nearby, and dinner unfolds with the sunset and the lights of the fishing bay."),
  "vehicle-rental": local("Вместо стандартного пакета вы получаете транспорт, который подходит именно вашему плану: байк для коротких поездок, автомобиль для семьи или машину с водителем для насыщенного дня по острову.", "Choose transport around your actual plans: a scooter for short local trips, a car for the family, or a chauffeured vehicle for a full day across the island."),
  "java-bromo-ijen": local("Это путешествие начинается задолго до рассвета и проходит через два совершенно разных вулканических мира. Бромо встречает вас морем тумана, а Иджен — суровым кратером, серными пейзажами и дорогой через Восточную Яву.", "This journey begins long before sunrise and moves through two very different volcanic worlds. Bromo rises above a sea of mist; Ijen follows with a raw crater landscape and the long roads of East Java."),
  "java-yogyakarta": local("Джокьякарта раскрывается слоями: рассвет у Боробудура, каменные башни Прамбанана, дворцы, ремесленные кварталы и живая городская культура между древними памятниками.", "Yogyakarta reveals itself in layers: morning light at Borobudur, the stone towers of Prambanan, royal history, artisan neighbourhoods, and a living city culture between ancient landmarks."),
};

const auditedPriceAdjustments: Partial<Record<string, TourPackage["price"]>> = {
  kintamani: { status: "indicative", currency: "USD", label: local("$66 / авто", "$66 / car") },
  "northwest-bali": { status: "indicative", currency: "USD", label: local("$78 / авто", "$78 / car") },
  "east-bali": { status: "indicative", currency: "USD", label: local("$78 / авто", "$78 / car") },
  "batur-sunrise": { status: "indicative", currency: "USD", label: local("$84 / гость", "$84 / guest") },
  "nusa-penida": { status: "indicative", currency: "USD", label: local("$96 / гость", "$96 / guest") },
};

export const packages: TourPackage[] = basePackages.map((item) => ({
  ...item,
  price: auditedPriceAdjustments[item.id] || item.price,
  experience: stories[item.id] || item.experience,
}));
