const images = {
  rice: 'https://images.pexels.com/photos/33720812/pexels-photo-33720812.jpeg?auto=compress&cs=tinysrgb&w=1600',
  coast: 'https://images.pexels.com/photos/32021944/pexels-photo-32021944.jpeg?auto=compress&cs=tinysrgb&w=1600',
  sunset: 'https://images.pexels.com/photos/33626257/pexels-photo-33626257.jpeg?auto=compress&cs=tinysrgb&w=1600'
};

const packages = [
  {id:'UBD',name:'Убуд и сердце Бали',family:'Central Bali',price:'от $60',duration:'9–10 часов',image:images.rice,stops:'водопады · Убуд · рисовые террасы'},
  {id:'EST',name:'Восточный Бали',family:'East Bali',price:'от $70',duration:'10–12 часов',image:images.sunset,stops:'храмы · водные сады · побережье'},
  {id:'NTH',name:'Северный Бали',family:'North Bali',price:'от $75',duration:'11–12 часов',image:images.rice,stops:'озёра · горы · водопады'},
  {id:'STH',name:'Южный Бали и закат',family:'South Bali',price:'от $55',duration:'8–10 часов',image:images.sunset,stops:'пляжи · Улувату · закат'},
  {id:'PEN',name:'Нуса-Пенида',family:'Island',price:'от $80 / чел.',duration:'11–12 часов',image:images.coast,stops:'запад или восток · локальный трансфер'},
  {id:'CST',name:'Ваш частный маршрут',family:'Custom',price:'по запросу',duration:'гибко',image:images.coast,stops:'ваш темп · ваши интересы · консультация'}
];

const state = {
  selected:'UBD',tier:'Essential',status:'enquiry',view:'customer',submitted:false,consent:false,
  name:'',whatsapp:'',email:'',channel:'WhatsApp',date:'',guests:'2',pickup:'',notes:''
};

const statuses = ['enquiry','qualified','quoted','awaiting confirmation','confirmed','handed off','in progress','completed'];
const escapeHTML = value => String(value || '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const selectedPackage = () => packages.find(item => item.id === state.selected) || packages[0];
const mediaStyle = item => `--image:url('${item.image}')`;

function nav(){return `<header class="nav"><div class="brand"><span class="brand-mark">B</span><span>BALI · БЛИЖЕ</span></div><div class="nav-links"><span>Маршруты</span><span>Как всё проходит</span><span>Команда</span></div><button class="btn secondary" data-action="jump-form">Обсудить поездку</button></header>`}
function proof(){return `<div class="proof"><div><b>Один контакт</b><span class="small">От первого вопроса до дня тура</span></div><div><b>Цена в USD</b><span class="small">RUB / IDR — в персональном расчёте</span></div><div><b>Местная команда</b><span class="small">Подтверждается до бронирования</span></div></div>`}
function packageCards(limit=6){return `<div class="package-grid">${packages.slice(0,limit).map(item=>`<article class="card package-card ${state.selected===item.id?'selected':''}"><div class="media" style="${mediaStyle(item)}"></div><div class="card-body"><div class="status">пример · нужен запрос</div><h3>${item.name}</h3><p class="small">${item.stops}</p><div class="package-meta"><div><div class="price">${item.price}</div><div class="small">Draft / indicative</div></div><div class="small">${item.duration}</div></div><div class="package-actions"><button class="btn dark" data-action="select-package" data-package="${item.id}">Выбрать</button><span class="chip">Essential / Practical</span></div></div></article>`).join('')}</div>`}
function tierSelector(){return `<div class="package-actions"><button type="button" class="chip ${state.tier==='Essential'?'active':''}" data-action="tier" data-tier="Essential">Essential</button><button type="button" class="chip ${state.tier==='Practical'?'active':''}" data-action="tier" data-tier="Practical">Practical</button></div>`}
function enquiryForm(dark=false){const item=selectedPackage();return `<div id="enquiry-form">${state.submitted?'<div class="success">Заявка собрана в памяти прототипа. Ничего не отправлено.</div>':''}<form class="form" data-form="enquiry"><div><div class="eyebrow">Ваш запрос</div><h2 style="font-size:38px;margin-bottom:8px">${item.name}</h2><p class="${dark?'lead':'muted'}">${state.tier} · ${item.price} · точная цена после уточнения деталей</p>${tierSelector()}</div><div class="form-grid"><div class="field"><label>Имя</label><input data-field="name" value="${escapeHTML(state.name)}" placeholder="Как к вам обращаться"></div><div class="field"><label>WhatsApp с кодом страны *</label><input data-field="whatsapp" value="${escapeHTML(state.whatsapp)}" placeholder="+7 …" required></div><div class="field"><label>Дата или период</label><input data-field="date" value="${escapeHTML(state.date)}" placeholder="Например, 18–21 августа"></div><div class="field"><label>Гостей</label><select data-field="guests">${['1','2','3','4','5','6+'].map(n=>`<option ${state.guests===n?'selected':''}>${n}</option>`).join('')}</select></div><div class="field"><label>Предпочтительный канал</label><select data-field="channel">${['WhatsApp','Telegram','VK','Email'].map(n=>`<option ${state.channel===n?'selected':''}>${n}</option>`).join('')}</select></div><div class="field"><label>Email — если нужен</label><input type="email" data-field="email" value="${escapeHTML(state.email)}" placeholder="Опционально"></div></div><div class="field"><label>Отель или район</label><input data-field="pickup" value="${escapeHTML(state.pickup)}" placeholder="Можно сообщить позже"></div><div class="field"><label>Пожелания</label><textarea data-field="notes" placeholder="Темп, интересы, особые потребности">${escapeHTML(state.notes)}</textarea></div><label class="small"><input type="checkbox" data-field="consent" ${state.consent?'checked':''} required> Я согласен(на), чтобы команда связалась со мной по заявке.</label><div class="package-actions"><button class="btn" type="submit">Собрать заявку</button><button class="btn ${dark?'secondary':'dark'}" type="button" data-action="preview-wa">Показать шаблон WhatsApp</button></div><p class="small">Prototype: форма, email и WhatsApp не отправляются.</p></form></div>`}
function stateSummary(){const item=selectedPackage();return `<aside class="summary"><div class="eyebrow">Booking summary · prototype</div><h3>${item.name}</h3><dl><dt>Status</dt><dd>${state.status}</dd><dt>Tier</dt><dd>${state.tier}</dd><dt>Guests</dt><dd>${escapeHTML(state.guests)}</dd><dt>Date</dt><dd>${escapeHTML(state.date)||'pending'}</dd><dt>Pickup</dt><dd>${escapeHTML(state.pickup)||'pending'}</dd><dt>Channel</dt><dd>${escapeHTML(state.channel)}</dd><dt>Availability</dt><dd>confirmation required</dd></dl><div class="state-json">${escapeHTML(JSON.stringify({package:item.id,tier:state.tier,status:state.status,contact:state.whatsapp?'provided':'missing',partner:'pending'},null,2))}</div><button class="btn secondary" style="margin-top:18px" data-action="advance">Simulate next state</button></aside>`}

function renderA(){return `<div class="shell a">${nav()}<section class="a-hero"><div><div class="eyebrow">Частные путешествия · живая консультация</div><h1>Ваш Бали начинается с разговора.</h1><p class="lead">Сначала понимаем ваш ритм, даты и бюджет. Затем показываем понятный вариант и подтверждаем местную команду.</p><button class="btn" data-action="jump-packages">Посмотреть маршруты</button><div class="a-proof">${proof()}</div></div><div class="media a-visual" style="${mediaStyle(packages[0])}"><div class="caption"><div><div class="eyebrow">Media atmosphere</div><b>Не доказательство пакета</b></div><div><b>01 / BALI</b><div class="small" style="color:white">Pexels provenance in MEDIA.md</div></div></div></div></section><section class="section light"><div class="journey-intro"><div><div class="eyebrow">Маршруты для старта</div><h2>Выберите направление. Детали соберём вместе.</h2></div><p class="lead">Цены — ориентир для пилота. Наличие, билеты и состав Practical подтверждаются вручную до реального бронирования.</p></div><div id="packages" style="margin-top:45px">${packageCards()}</div></section><section class="section"><div class="concierge-stage"><div class="guide-list"><div class="active">01 · Выберите маршрут</div><div>02 · Расскажите детали</div><div>03 · Получите предложение</div><div>04 · Подтвердите команду</div></div><div class="enquiry-panel">${enquiryForm()}</div></div></section><section class="section"><div class="journey-intro"><div><div class="eyebrow">Что увидит команда</div><h2>Не чат, а структурированный handoff.</h2></div>${stateSummary()}</div></section></div>`}

function renderB(){return `<div class="shell b">${nav()}<section class="section"><div class="b-head"><div><div class="eyebrow">Каталог сначала</div><h1>Сравните. Выберите. Уточните.</h1></div><p class="lead">Подходит клиенту, который хочет быстро увидеть географию, длительность и уровень включений до разговора.</p></div></section><section class="section" style="padding-top:0"><div class="catalogue-layout"><div>${packageCards()}<div style="margin-top:24px" class="compare-strip"><div class="compare-item"><div class="eyebrow">Essential</div><h3>Контролируемая базовая стоимость</h3><ul><li>Транспорт и координация</li><li>Доплаты видны отдельно</li><li>Та же поддержка и безопасность</li></ul></div><div class="compare-item"><div class="eyebrow">Practical</div><h3>Меньше расчётов на месте</h3><ul><li>Больше включённых компонентов</li><li>Проще координация</li><li>Точный состав после подтверждения</li></ul></div></div></div><aside class="brief-panel">${enquiryForm(true)}</aside></div></section><section class="section" style="background:var(--night);color:white"><div class="journey-intro"><div><div class="eyebrow">После запроса</div><h2>Команда получает brief, а не пересланный чат.</h2></div>${stateSummary()}</div></section></div>`}

function timeline(){const current=Math.max(0,statuses.indexOf(state.status));return `<div class="timeline">${statuses.slice(0,6).map((s,i)=>`<div class="timeline-step ${i<current?'done':i===current?'current':''}"><span class="dot">${i<current?'✓':String(i+1).padStart(2,'0')}</span><div><h3>${s}</h3><p class="small" style="color:rgba(255,255,255,.55)">${['Запрос создан','Детали поездки собраны','Цена и состав отправлены','Команда Бали проверяется','Клиент подтвердил условия','Операционный handoff принят'][i]}</p></div></div>`).join('')}</div>`}
function operatorWorkspace(){const item=selectedPackage();return `<div class="workspace"><div class="workspace-card">${state.view==='customer'?enquiryForm():`<div class="eyebrow">Operator handoff</div><h2 style="font-size:40px">${item.name}</h2><div class="state-list"><div class="state-row"><span>Customer contact</span><b>${state.whatsapp?'Provided':'Missing'}</b></div><div class="state-row"><span>Availability</span><b>Confirmation required</b></div><div class="state-row"><span>Supplier</span><b>Pending</b></div><div class="state-row"><span>Media status</span><b>Atmosphere only</b></div><div class="state-row"><span>Publishability</span><b>Pilot</b></div></div><button class="btn dark" style="margin-top:20px" data-action="advance">Simulate next state</button>`}</div><div class="operator-card workspace-card">${stateSummary()}</div></div>`}
function renderC(){return `<div class="shell c">${nav()}<section class="c-hero media" style="${mediaStyle(packages[4])}"><div><div class="eyebrow">Прозрачный путь · от идеи до Бали</div><h1>Всегда понятно, что уже решено.</h1><p class="lead">Клиент видит следующий шаг. Команда видит данные, которые ещё нужно подтвердить.</p><button class="btn" data-action="jump-board">Открыть journey</button></div></section><section class="section" id="journey-board"><div class="journey-tabs"><button class="chip ${state.view==='customer'?'active':''}" data-action="view" data-view="customer">Customer view</button><button class="chip ${state.view==='operator'?'active':''}" data-action="view" data-view="operator">Operator view</button></div><div class="journey-board">${timeline()}${operatorWorkspace()}</div></section><section class="section light"><div class="journey-intro"><div><div class="eyebrow">Каталог остаётся доступным</div><h2>Маршрут можно сменить без потери brief.</h2></div><p class="lead">В production данные должны жить в booking summary. В прототипе состояние хранится только в памяти браузера.</p></div><div style="margin-top:40px">${packageCards(3)}</div></section></div>`}

const variants={A:{name:'Guided concierge',render:renderA},B:{name:'Catalogue to brief',render:renderB},C:{name:'Journey transparency',render:renderC}};
const keys=Object.keys(variants);const params=new URLSearchParams(location.search);let current=variants[params.get('variant')]?params.get('variant'):'A';
function show(key){current=key;document.getElementById('app').innerHTML=variants[key].render();document.getElementById('variant-label').textContent=`${key} — ${variants[key].name}`;params.set('variant',key);history.replaceState(null,'',`${location.pathname}?${params}`)}
function cycle(delta){const i=keys.indexOf(current);show(keys[(i+delta+keys.length)%keys.length])}
function scrollToSelector(selector){requestAnimationFrame(()=>document.querySelector(selector)?.scrollIntoView({behavior:'smooth',block:'start'}))}
document.getElementById('previous').addEventListener('click',()=>cycle(-1));document.getElementById('next').addEventListener('click',()=>cycle(1));
document.addEventListener('input',e=>{const field=e.target.dataset.field;if(field)state[field]=e.target.type==='checkbox'?e.target.checked:e.target.value});
document.addEventListener('submit',e=>{if(!e.target.matches('[data-form="enquiry"]'))return;e.preventDefault();state.submitted=true;state.status='qualified';show(current);scrollToSelector('#enquiry-form')});
document.addEventListener('click',e=>{const button=e.target.closest('[data-action]');if(!button)return;const action=button.dataset.action;if(action==='select-package'){state.selected=button.dataset.package;show(current);scrollToSelector('#enquiry-form')}if(action==='tier'){state.tier=button.dataset.tier;show(current);scrollToSelector('#enquiry-form')}if(action==='advance'){const index=statuses.indexOf(state.status);state.status=statuses[Math.min(index+1,statuses.length-1)];show(current);scrollToSelector(current==='C'?'#journey-board':'#enquiry-form')}if(action==='view'){state.view=button.dataset.view;show(current);scrollToSelector('#journey-board')}if(action==='jump-packages')scrollToSelector('#packages');if(action==='jump-board')scrollToSelector('#journey-board');if(action==='jump-form')scrollToSelector('#enquiry-form');if(action==='preview-wa'){const item=selectedPackage();alert(`WhatsApp preview — ничего не отправлено:\n\nЗдравствуйте! Хочу узнать о частном туре на Бали.\nМаршрут / пакет: ${item.name} — ${state.tier}\nДата: ${state.date||'{date}'}\nКоличество гостей: ${state.guests}\nОтель или район: ${state.pickup||'{pickup_area}'}\nПожелания: ${state.notes||'{notes}'}\n\nПожалуйста, подготовьте пример расчёта в USD и RUB/IDR.`)}});
document.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName)||document.activeElement?.isContentEditable)return;if(e.key==='ArrowLeft')cycle(-1);if(e.key==='ArrowRight')cycle(1)});
show(current);
